### ISSUE TITLE
 arf-multilanguage.zip is missing

### ISSUE THREAD

**Issue by stephaneDelos** [corradolorefice/clr-multi-language-labels#1]
Hello,

i cant find the zip file mentionned in the readme.

Can you help me in installing and testing this qlik plugin ?

Should i compile or generate something ?

Thanks for your help !

Stéphane

**Comment by corradolorefice** [comment]
Hi,
added the demo application that was missing, knowledge about Qlik extensions is needed to test it, please refer to help.qlik.com for further info.
Regards
Corrado
